Fix multi gpu rendering
den13k/RadeonProRender-Baikal pull request #2
Opened 2018-07-17 13:36 UTC by AlexanderVeselov

2018-07-19 11:29 UTC, den13k requested changes

2018-07-19 11:29 UTC, den13k commented on Baikal/SceneGraph/scene_object.cpp
> +        assert(controller_id >= 0 && controller_id < sizeof(std::uint32_t) * 8);
the first one is always true.
pls. remove

2018-07-19 11:29 UTC, den13k commented on Baikal/SceneGraph/scene_object.cpp
> +        if (g_scene_controller_id == -1)
is this possible?
assert should be enough

2018-07-19 11:29 UTC, den13k commented on Baikal/SceneGraph/scene_object.cpp
> +            if (g_scene_controller_id == -1)
is this possible?

2018-07-19 11:29 UTC, den13k commented on Baikal/Controllers/scene_controller.inl
> +        : m_id(g_next_scene_controller_id++)
does scene controllers persist while app is running? Is it possible that a controller will be deleted and the created with another id?

2018-07-19 11:29 UTC, den13k commented on Baikal/SceneGraph/scene_object.cpp
> +            dirty = ((int)m_dirty & (1 << g_scene_controller_id)) == (1 << g_scene_controller_id);
pls. introduce an additional variable and simplify the statement.

2018-07-19 11:29 UTC, den13k commented on Baikal/SceneGraph/scene_object.cpp
> +                m_dirty &= ~(1 << g_scene_controller_id);
pls. add a comment

2018-07-19 11:30 UTC, den13k commented
please consider to use std::bitset

2018-07-20 05:26 UTC, den13k commented on BaikalStandalone/Application/cl_render.cpp
> +        ConfigManager::CreateConfigs(
why there is no exception handling anymore?

2018-07-20 05:26 UTC, den13k commented on Baikal/SceneGraph/scene_object.h
> +        static const int kMaxDirtyBits = 32;
pls add a comment here about the value

2018-07-20 10:53 UTC, den13k commented on Baikal/Controllers/scene_controller.inl
> +        : m_id(g_next_scene_controller_id++)
discussed

2018-07-20 10:55 UTC, den13k commented on BaikalStandalone/Application/cl_render.cpp
> +        ConfigManager::CreateConfigs(
discussed

2018-07-20 10:59 UTC, den13k commented on BaikalStandalone/Utils/config_manager.cpp
> +            bool create_secondary = true;
pls. rename to createWithoutInterop or something similar

2018-07-20 11:27 UTC, AlexanderVeselov commented on Baikal/SceneGraph/scene_object.h
> +        static const int kMaxDirtyBits = 32;
Done

2018-07-20 11:27 UTC, AlexanderVeselov commented on BaikalStandalone/Utils/config_manager.cpp
> +            bool create_secondary = true;
Done

2018-07-20 11:32 UTC, den13k approved these changes

2018-07-31 14:02 UTC, closed without merging